// Movies - Endpoints
const MoviePopular = 'https://api.themoviedb.org/3/movie/popular?language=fr-FR';
const MovieTopRated = 'https://api.themoviedb.org/3/movie/top_rated?language=fr-FR';
const MovieNowPlaying = 'https://api.themoviedb.org/3/movie/now_playing?language=fr-FR';
const MovieUpcoming = 'https://api.themoviedb.org/3/movie/upcoming?language=fr-FR';
const MovieSimilar = 'https://api.themoviedb.org/3/movie/{movie_id}/similar?language=fr-FR';
const MovieRecommendations = 'https://api.themoviedb.org/3/movie/{movie_id}/recommendations?language=fr-FR';
const MovieSearch = 'https://api.themoviedb.org/3/search/movie?language=fr-FR';
const MovieDetails = 'https://api.themoviedb.org/3/movie/{movie_id}?language=fr-FR';
const MovieCredits = 'https://api.themoviedb.org/3/movie/{movie_id}/credits?language=fr-FR';
const MovieImages = 'https://api.themoviedb.org/3/movie/{movie_id}/images?language=fr-FR';
const MovieVideos = 'https://api.themoviedb.org/3/movie/{movie_id}/videos?language=fr-FR';
const MovieReviews = 'https://api.themoviedb.org/3/movie/{movie_id}/reviews?language=fr-FR';
const MovieWatchProviders = 'https://api.themoviedb.org/3/movie/{movie_id}/watch/providers?language=fr-FR';
const MovieDiscoverTopRated = 'https://api.themoviedb.org/3/discover/movie?sort_by=vote_average.desc&vote_count.gte=1000&language=fr-FR';
const MovieDiscoverPopular = 'https://api.themoviedb.org/3/discover/movie?sort_by=popularity.desc&language=fr-FR';
const MovieDiscoverTopRevenue = 'https://api.themoviedb.org/3/discover/movie?sort_by=revenue.desc&language=fr-FR';

// Series - Endpoints
const SeriesPopular = 'https://api.themoviedb.org/3/tv/popular?language=fr-FR';
const SeriesTopRated = 'https://api.themoviedb.org/3/tv/top_rated?language=fr-FR';
const SeriesAiringToday = 'https://api.themoviedb.org/3/tv/airing_today?language=fr-FR';
const SeriesOnTheAir = 'https://api.themoviedb.org/3/tv/on_the_air?language=fr-FR';
const SeriesSimilar = 'https://api.themoviedb.org/3/tv/{tv_id}/similar?language=fr-FR';
const SeriesRecommendations = 'https://api.themoviedb.org/3/tv/{tv_id}/recommendations?language=fr-FR';
const SeriesSearch = 'https://api.themoviedb.org/3/search/tv?language=fr-FR';
const SeriesDetails = 'https://api.themoviedb.org/3/tv/{tv_id}?language=fr-FR';
const SeriesCredits = 'https://api.themoviedb.org/3/tv/{tv_id}/credits?language=fr-FR';
const SeriesImages = 'https://api.themoviedb.org/3/tv/{tv_id}/images?language=fr-FR';
const SeriesVideos = 'https://api.themoviedb.org/3/tv/{tv_id}/videos?language=fr-FR';
const SeriesReviews = 'https://api.themoviedb.org/3/tv/{tv_id}/reviews?language=fr-FR';
const SeriesWatchProviders = 'https://api.themoviedb.org/3/tv/{tv_id}/watch/providers?language=fr-FR';
const SeriesDiscoverTopRated = 'https://api.themoviedb.org/3/discover/tv?sort_by=vote_average.desc&vote_count.gte=1000&language=fr-FR';
const SeriesDiscoverPopular = 'https://api.themoviedb.org/3/discover/tv?sort_by=popularity.desc&language=fr-FR';
const SeriesDiscoverTopRevenue = 'https://api.themoviedb.org/3/discover/tv?sort_by=revenue.desc&language=fr-FR';
